import { Game, GameAttributes } from './types';
import { calculateScore } from './utils';

const GAME_DESCRIPTIONS: Record<string, string> = {
  "Roblox": "Extraction platform aimed at children. Users create content, Roblox reaps the rewards. Extremely addictive due to social pressure, endless content, and manipulative monetization. Predator risks in social environments. 28-minute average sessions = designed for time wasting.",
  "Honor of Kings": "World's largest MOBA by revenue ($2.4B). Competitive stress, toxic community risks, ranking obsession. Short matches but high frequency creates addiction pattern. Violence is stylized but constant.",
  "Minecraft": "Exception in gaming. Creative sandbox without violence (Peaceful mode), no pay-to-win, promotes spatial thinking and planning. Can be time-consuming due to endless possibilities. Premium model protects against exploitation.",
  "Fortnite": "Battle royale with high rajas (100 players, 1 winner). Constant updates create FOMO. Battlepass and cosmetic economy. Less violent than competitors but still based on elimination. Cultural phenomenon with social pressure.",
  "Counter-Strike 2": "Pure skill-based shooter. No pay-to-win but high competitive stress. Violence is central but not glorified. Toxic community. Requires high concentration (ekagrata) but focused on killing.",
  "League of Legends": "Notoriously toxic community. Matches of 30-45 min where one player can ruin the team. Ranking obsession. High strategic depth (viveka) but emotionally exhausting. 'Just one more game' syndrome extreme.",
  "PUBG/PUBG Mobile": "Battle royale pioneer. 100 players, survival stress. Tension between long quiet periods and sudden violent confrontations. Mobile version extra addictive due to accessibility. Realistic violence aesthetics.",
  "Call of Duty (franchise)": "Glorification of violence as core product. Militaristic propaganda elements. Fast dopamine loops. Multiplayer toxicity. Annual releases = planned obsolescence. Critic-user score gap suggests dissatisfaction.",
  "GTA V": "Open world crime simulator. Player is rewarded for murder, theft, and destruction. 12 years old but still popular due to online mode. Strong dissociation risks. Satirical tone masks violence normalization.",
  "Dota 2": "Most complex MOBA. Extremely high skill ceiling = viveka training. But also longest matches (45-60 min), most toxic community, and highest frustration. $40M prize pools create 'pro-dream' illusion.",
  "Candy Crush Saga": "Casual puzzle game. Fair F2P model compared to competitors. But designed for micropayments at frustration points. No violence, low stimulation. 11-year lifespan suggests working but not harmful model.",
  "Mobile Legends: Bang Bang": "Honor of Kings clone for Southeast Asia. Same MOBA problems: toxicity, ranking obsession, competitive stress. Shorter matches than LoL/Dota but higher frequency.",
  "Garena Free Fire": "Battle royale optimized for low-end devices. Popular in LATAM/SEA. More aggressive monetization than PUBG. Shorter matches = faster dopamine loops. Pay-to-win elements in some regions.",
  "Path of Exile 2": "ARPG with extreme depth. Loot grind can become obsessive. Dark, violent aesthetics. Complex enough for viveka training but addictive progression loops. Free-to-play with fair monetization.",
  "Marvel Rivals": "Hero shooter with Marvel IP. Team-based = less toxic than solo-ranked. But still violence as core. New game so addiction patterns not fully established yet.",
  "Baldur's Gate 3": "RPG masterpiece. High narrative quality, moral choices that have consequences. Violence present but contextual. Long playtime (100+ hours) can be problematic. Supports co-op = positive sanga.",
  "Royal Match": "Candy Crush competitor. Same model: casual puzzles with paywalls at difficult levels. $1.9B revenue suggests effective monetization. No violence but designed for engagement maximization.",
  "Clash Royale": "Real-time strategy with cards. Skill-based but with gacha elements for cards. Short matches (3 min) are double-edged: less time loss per session but more 'just one more' moments.",
  "Rust": "Survival with PvP focus. Extreme toxicity, griefing as gameplay. Offline raiding = constant stress. Nudity and violence. Can teach vairagya (you lose everything) but via trauma, not insight.",
  "ARC Raiders": "New extraction shooter. PvPvE stress, loot-loss mechanic. Genre inherently stressful and addictive. Too new for full assessment but follows known patterns.",
  "Stardew Valley": "Gold standard for relaxed gaming. Farming sim without violence, own pace, no paywalls. Can be time-consuming ('just one more day') but plants positive samskaras of care and patience.",
  "Brawl Stars": "Supercell quality. Short matches, skill-based, less toxic due to lack of chat. Gacha elements for characters. Better than most mobile games but still designed for engagement.",
  "Pokémon TCG Pocket": "Digital card game with gacha. Fair model according to reviews. Strategic depth without realtime stress. Collector's urge can become problematic. No violence.",
  "Genshin Impact": "Gacha game with AAA production value. Generous for F2P but designed to milk whales. Anime aesthetics, light story. Daily tasks create return patterns. Open world = dissociation risk.",
  "Warframe": "F2P shooter with fair monetization. Grinding is the gameplay. Co-op focus reduces toxicity. Violence is central but against alien enemies. Complex systems can be overwhelming.",
  "Honkai: Star Rail": "Genshin's turn-based sister. Same gacha model but less open world dissociation. Daily energy system limits playtime (double-edged). Anime violence, light.",
  "Hollow Knight: Silksong": "Metroidvania masterpiece. High difficulty = frustration tolerance and vairagya training. Atmospheric violence but not glorified. Finite experience with clear endpoint.",
  "Monster Hunter Wilds": "Co-op centered action. Hunting monsters = violence but against fantasy creatures. Strong sanga due to teamwork focus. Grinding for gear can become obsessive. No PvP toxicity.",
  "Apex Legends": "Battle royale with team focus. Less toxic than solo BRs. But still killing 60 players as goal. Seasonal FOMO. Cheating problems diminish experience.",
  "Terraria": "2D sandbox adventure. Violence against monsters but in playful, pixel-art context. Huge amount of content can be time-consuming. Co-op possibility. Fair premium model.",
  "Elden Ring": "FromSoftware masterpiece. Extreme difficulty teaches true vairagya and frustration tolerance. Violence is dark and meaningful. Can be time-consuming but has endpoint. No multiplayer toxicity.",
  "Call of Duty Mobile": "Console CoD on mobile. Same violence issues but with mobile addiction mechanisms. Accessibility increases risk for youth.",
  "Subway Surfers": "Endless runner. No violence, simple gameplay. Designed for short sessions but can become addictive. Ad-driven. Relatively harmless.",
  "Clash of Clans": "Base builder pioneer. Timer mechanisms fragment your day. Clan pressure for activity. But 12 years relevant = proven model. Less aggressive than newer competitors.",
  "8 Ball Pool": "Billiards simulation. Skill-based, no violence, natural endpoints per match. Relatively healthy mobile game. Social elements without toxicity.",
  "Ludo King": "Digital board game. Traditional game without modern addiction mechanisms. Social component. Cultural phenomenon in India. One of the healthier mobile options.",
  "Cyberpunk 2077": "Open world RPG in dystopian setting. Violence, drugs, sexuality as themes. Strong narrative, but dark samskaras. Redemption story after bad launch shows developer integrity.",
  "Dead by Daylight": "Asymmetrical horror. One killer, four survivors. Stressful, dark, but also strategic. Unique gameplay but horror samskaras. Strong community despite themes.",
  "Red Dead Redemption 2": "Narrative masterpiece. Violence in Western context with moral consequences. Slow pace promotes presence. But 100+ hours and open world = dissociation risk.",
  "Palworld": "'Pokémon with guns'. Controversial concept. Survival mechanics + creature collection. Violence against cute creatures is problematic. Viral hit now stabilized.",
  "Bongo Cat": "Casual music game. Cute, innocent, short sessions. No violence, no manipulative monetization. Viral hit that is actually harmless.",
  "Euro Truck Simulator 2": "Niche perfection. Driving, delivering, relaxing. No violence, meditative quality. Can be time-consuming but plants no negative samskaras. Radio integration.",
  "Schedule I": "Drug dealer simulation. Morally problematic premise but gameplay is business management. No direct violence but crime as theme. High ratings suggest quality, not ethics.",
  "R.E.P.O.": "Co-op extraction game. Playing together reduces negative effects. 'Friendslop' genre = social gaming. Less competitive, more collaborative.",
  "Team Fortress 2": "17-year-old classic. Cartoon violence in team context. Less serious than modern shooters. Community-driven but also decayed. Loot boxes are problematic.",
  "Geometry Dash": "Rhythm-based platformer. Extreme difficulty = frustration tolerance training. No violence, pure skill. Short levels but perfectionism can become obsessive.",
  "RimWorld": "Colony sim with dark humor. War crimes as gameplay possibilities. Extremely addictive due to emergent storytelling. Moral distance due to 'it's just a game' attitude.",
  "Left 4 Dead 2": "Zombie co-op shooter. 15 years old, still active. Violence against undead. Strong teamwork requirement = positive sanga. Finite campaigns.",
  "Project Zomboid": "Survival horror. Slow, methodical, stressful. Permadeath teaches vairagya. Dark thematically but deep. Can become extremely time-consuming.",
  "VRChat": "Social VR platform. No gameplay, pure social interaction. Can facilitate positive connections but also dissociation in virtual worlds. Depends on who you meet.",
  "Mario Kart 8 Deluxe/World": "Family-friendly racer. Competitive but playful. No violence, social gameplay. Best-selling Switch game. Short races = natural endpoints. Ideal for shared play.",
  "Pokémon Scarlet/Violet/Z-A": "Pokémon formula. Collecting, training, fighting. Light violence, child-rich. Technical issues show rushed development. Can create grinding obsession.",
  "Animal Crossing: New Horizons": "Ultimate relaxed experience. No violence, own pace, creativity. Real-time clock can create FOMO. 'Enforced positivity' community. Decoration obsession possible.",
  "Super Smash Bros. Ultimate": "Party fighting game. Violence but cartoonish and playful. Competitive scene can be intense. Ideal for social gaming. 36M+ sold = cultural phenomenon.",
  "Zelda: Tears of the Kingdom": "Open world masterpiece. Puzzles, exploration, creativity. Violence against monsters but in fantasy context. 100+ hours content can be time-consuming. High viveka through physics puzzles.",
  "Splatoon 3": "Unique shooter: ink instead of blood. Competitive but child-friendly. Nintendo's answer to toxic shooter culture. Short matches, colorful, playful.",
  "EA Sports FC 26": "Football simulation. Ultimate Team is gacha mechanism. Annual releases = planned obsolescence. No direct violence but gambling-like pack openings. License monopoly.",
  "Hogwarts Legacy": "Harry Potter RPG. Violence in magical context. Controversies around J.K. Rowling. Open world with collection elements. Strong narrative, finite experience.",
  "Rainbow Six Siege X": "Tactical shooter. High skill ceiling, teamwork required. Realistic violence aesthetics. Toxic community. Seasonal content = FOMO.",
  "Forza Horizon 5": "Open world racer. No violence, beautiful world. Can be relaxing but also grinding for cars. Festival atmosphere is positive.",
  "War Thunder": "Military vehicle simulator. Grinding hell with pay-to-progress. High engagement but poor user score reveals frustration. Realistic warfare.",
  "Helldivers 2": "Co-op shooter with satirical tone. Starship Troopers aesthetic. Teamwork central, less toxic. PSN controversy showed corporate issues. Violence but with a wink.",
  "Destiny 2": "Live service shooter in decline. Content vault removes paid content. FOMO-driven seasons. Gameplay is solid but business model is problematic.",
  "FIFA/EA FC franchise": "Same as EA Sports FC. Ultimate Team gambling. Annual milking machine. Esports legitimizes but does not change core.",
  "The Sims 4": "Life simulation. No violence, creative expression. Now F2P but DLC-rich. Can be dissociative due to 'other life' fantasy. Inclusive and diverse.",
  "ARK: Survival Ascended": "Paid remake controversy. Dinosaur survival. Grinding, taming, base building. Toxic PvP servers. Original game was already problematic.",
  "Last War: Survival": "WARNING: Whale-milker. $2.2B revenue from heavy spenders. Pay-to-win, timer hell, social pressure. Avoid strongly. Mobile gaming at its worst.",
  "Whiteout Survival": "Same warning as Last War. Survival city builder with aggressive monetization. Rankings dominated by payers. Manipulative mechanics.",
  "MONOPOLY GO!": "Board game IP with mobile monetization. Event-driven spending. Less aggressive than Last War but still designed for maximum extraction. FOMO mechanics.",
  "Coin Master": "WARNING: Gambling mechanics. Slot machine core with social pressure. $910M revenue from addictive loops. No skill, pure chance and payment.",
  "Block Blast!": "Tetris-like puzzle. 356M downloads suggests broad appeal. Ad-driven. Relatively harmless but little depth.",
  "Pokémon GO": "Augmented reality collector. Was revolutionary, now event-driven FOMO. Moves you physically (good) but with manipulative incentives. Community Days create pressure.",
  "Clair Obscur: Expedition 33": "Turn-based RPG. GOTY 2025 winner. Narrative quality, artistic vision. Finite experience with clear story. Violence in fantasy context.",
  "Kingdom Come: Deliverance II": "Historical RPG. Realistic medieval world. Violence is consequential and grim. High immersion can be dissociative. Deep but dark.",
  "Battlefield 6": "Large-scale warfare shooter. Franchise redemption after 2042 fiasco. Teamwork focus but still militaristic glorification of violence.",
  "Total War: Warhammer III": "Strategy with Warhammer setting. Complex systems = viveka training. Violence is abstract (units, not individuals). Extremely time-consuming.",
  "Hearts of Iron IV": "WW2 grand strategy. Plays as nations, not individuals. Can 'gamify' war but also give historical understanding. Paradox addiction is real.",
  "Civilization VI": "4X classic. 'One more turn' syndrome extreme. Plays over millennia = abstraction of violence. Educational value but time black hole.",
  "Football Manager 26": "Spreadsheet football. No violence, pure management. Extremely addictive for target audience. Can feed obsessive micromanagement.",
  "Fallout 4": "Post-apocalyptic RPG. Violence, drugs, dark themes. Open world dissociation. TV show revival shows cultural impact. Moral choices present.",
  "PEAK": "Climbing simulator. No violence, skill-based, natural setting. Viral hit that actually offers positive experience. Frustration tolerance training.",
  "Delta Force": "Tencent tactical shooter. Chinese gaming company with known practices. Violence, competition, mobile focus suggests monetization aggression.",
  "Deep Rock Galactic": "Co-op mining shooter. 'Rock and Stone' culture = positive community. Dwarves, aliens, teamwork. Less serious violence. Community gold standard.",
  "FFXIV": "MMO with best community reputation. Narrative focus above grind. Monthly subscription = no gacha. But MMO time investment is huge.",
  "Where Winds Meet": "Chinese action RPG. Wuxia setting. Unknown in West, difficult to judge. Visually beautiful, gameplay details unclear.",
  "7 Days to Die": "Zombie survival. Minecraft + zombies. Violence against undead, base building. Co-op possibility. Can become very time-consuming.",
  "Township": "Casual city builder. Fair for mobile standards. Timer mechanics but less aggressive. No violence, productive feeling.",
  "Among Us": "Social deduction. Minimal monetization, short rounds. Huge cultural impact. 'Sus' became mainstream. Trust/betrayal as theme.",
  "Hay Day": "Supercell farming. Timer mechanics fragment day. Check-in patterns. But no violence, calm aesthetic. Less aggressive than competitors.",
  "Stumble Guys": "Fall Guys clone. Party game chaos. No violence, short rounds. Can be frustrating but also lighthearted. Social gaming.",
  "Pizza Ready": "Hyper-casual management. Short sessions, simple loops. Ad model. Innocent but also superficial.",
  "Vita Mahjong": "Traditional game digital. Skill-based, no violence. Genre resurgence (+189%). Healthy gaming option. Cognitive training.",
  "Dragon Quest XI": "JRPG classic. Turn-based, narrative rich. Violence in cartoon-fantasy context. Long playtime but finite experience. Positive themes.",
  "Gran Turismo 7": "Racing sim. No violence, focus on precision. Microtransaction controversy at launch now improved. Can become obsessive about times/collection.",
  "Asphalt 9": "Arcade racer. Mobile quality, gacha for cars. Fast races, flashy graphics. Less deep than console racers.",
  "DOOM: The Dark Ages": "Violence as art form. Extreme but cartoonish. High skill, fast gameplay. Short campaign = natural endpoint. Catharsis or desensitization?",
  "Avowed": "Obsidian RPG. First-person fantasy. Solid but not exceptional. Game Pass model = accessible. Violence in context.",
  "Ghost of Yotei": "Upcoming Sony exclusive. Samurai setting, open world. Ghost of Tsushima successor. Violent but artistic. Not yet assessable.",
  "Dispatch": "Steam Award winner. Rare perfect score alignment (97% Steam, 9.0 MC). Details unknown but consensus suggests quality.",
  "Sea of Thieves": "Pirate sandbox. Co-op focus, emergent stories. Violence but playful. Rare's comeback. Social gaming with friends."
};

const RAW_GAMES_DATA: any[] = [
  [1,"Roblox","Mobile, PC, Console","79.5M DAU","4.4★ iOS/Android","1 - Engagement Giants","Genuine grassroots platform; 28-min avg sessions prove authentic engagement",[2,4,2,1,2,2,2,2,1,2,5,5,4,3,2,4,4,5]],
  [2,"Honor of Kings","Mobile","~145M DAU","4.5★ regional","1 - Engagement Giants","World's largest MOBA by revenue ($2.4B). Legitimate esports",[2,5,2,1,3,4,1,3,2,2,5,4,3,2,3,4,3,4]],
  [3,"Minecraft","All platforms","~160M MAU","4.7★ mobile, 97% Steam","1 - Engagement Giants","15+ years organic growth. Premium model = no pay-to-win",[4,2,0,3,4,4,4,3,3,3,3,4,3,0,0,2,4,3]],
  [4,"Fortnite","All platforms","~220M MAU","4.0-4.5★","1 - Engagement Giants","#1 on PlayStation and Xbox 2025. Authentic cultural phenomenon",[2,5,2,1,3,4,1,3,2,2,5,4,3,3,3,4,4,4]],
  [5,"Counter-Strike 2","PC","1.4M Daily Concurrent","86% Very Positive","1 - Engagement Giants","Valve's flagship. 35M+ estimated MAU. Pure skill-based gameplay",[1,5,2,2,4,5,1,4,3,3,4,4,2,2,4,4,3,3]],
  [6,"League of Legends","PC","~130M MAU","Mixed (toxicity concerns)","1 - Engagement Giants","Declining from 180M peak but still massive",[1,5,2,1,4,4,0,3,2,3,5,5,3,3,3,4,2,5]],
  [7,"PUBG/PUBG Mobile","PC, Mobile","~280M MAU (Combined)","65% Steam (Mixed)","1 - Engagement Giants","⚠️ User score significantly lower than 87 critic score",[1,5,3,2,3,4,1,3,3,2,4,4,3,3,4,4,2,4]],
  [8,"Call of Duty (franchise)","All platforms","~90M MAU","68% Steam (Mixed)","1 - Engagement Giants","⚠️ 78 critic vs ~50 user Metacritic gap",[1,5,3,1,2,4,1,2,2,2,4,4,3,4,5,5,3,4]],
  [9,"GTA V","PC, Console","140K+ Concurrent Steam","85% Steam","1 - Engagement Giants","12 years old, still charting",[2,4,4,1,3,3,2,2,2,2,4,5,4,4,5,4,3,4]],
  [10,"Dota 2","PC","600-800K Concurrent","~80% Positive","1 - Engagement Giants","$40M+ annual prize pool. Organic esports ecosystem",[1,5,2,2,5,5,0,4,3,4,5,5,3,2,2,4,2,5]],
  [11,"Candy Crush Saga","Mobile","~250M MAU","4.7★","2 - Established Powerhouses","11 years sustained popularity. Fair F2P model",[3,2,1,2,2,3,3,3,2,1,4,3,2,1,0,3,1,3]],
  [12,"Mobile Legends: Bang Bang","Mobile","85M+ DAU","4.4★","2 - Established Powerhouses","Dominant in Southeast Asia",[2,5,2,1,3,4,1,3,2,2,5,4,3,2,3,4,3,4]],
  [13,"Garena Free Fire","Mobile","~187M DAU","4.1★","2 - Established Powerhouses","Optimized for low-end devices. Massive in LATAM/SEA",[1,5,3,1,2,4,1,2,2,2,5,4,3,3,4,4,3,4]],
  [14,"Path of Exile 2","PC","~200K Daily","88% Very Positive","2 - Established Powerhouses","2024's biggest ARPG launch. Organic hype",[2,4,3,2,4,4,2,4,3,3,4,5,3,2,2,3,2,4]],
  [15,"Marvel Rivals","PC, Console","~100K Concurrent","85% Very Positive","2 - Established Powerhouses","December 2024 breakout hit. Genuine word-of-mouth growth",[2,5,2,1,3,4,1,3,2,2,4,3,2,2,3,4,4,3]],
  [16,"Baldur's Gate 3","PC, Console","~90K Daily","97% Overwhelmingly Positive","2 - Established Powerhouses","GOTY 2023. Gold standard for RPGs",[4,3,2,3,5,4,4,3,4,4,3,5,4,1,2,3,4,4]],
  [17,"Royal Match","Mobile","50M+ MAU","4.7★","2 - Established Powerhouses","$1.9B revenue. Exceptional retention",[3,2,1,2,2,3,3,3,2,1,4,3,2,1,0,3,1,3]],
  [18,"Clash Royale","Mobile","~18M MAU","4.5★","2 - Established Powerhouses","$627.5M (+147% YoY). 9-year resurgence",[2,4,1,2,4,4,2,4,3,3,4,3,2,1,1,3,3,3]],
  [19,"Rust","PC","130K+ Concurrent","88% Very Positive","2 - Established Powerhouses","Survival stalwart. Consistent engagement",[1,5,3,3,3,4,1,4,3,3,4,5,3,3,4,4,3,4]],
  [20,"ARC Raiders","PC","~50K Concurrent","TBD (New)","2 - Established Powerhouses","2025 extraction shooter success",[1,5,3,2,3,4,1,3,3,2,4,4,3,3,4,4,3,4]],
  [21,"Stardew Valley","All platforms","60K+ Concurrent Steam","98% Overwhelmingly Positive","3 - Quality Performers","Highest-rated game on Steam. $15 indie beating $70 AAA",[5,2,0,4,3,4,5,3,4,3,3,4,3,0,0,1,4,3]],
  [22,"Brawl Stars","Mobile","40M+ DAU","4.4★","3 - Quality Performers","$9M+ esports prize pool. Skill-based gameplay",[2,4,1,2,3,4,2,3,3,2,4,3,2,1,2,4,4,3]],
  [23,"Pokémon TCG Pocket","Mobile","10M+ DAU","4.7★","3 - Quality Performers","App Store GOTY 2025. Fair gacha model",[3,3,1,2,4,4,3,3,3,2,4,3,2,1,0,3,3,3]],
  [24,"Genshin Impact","Mobile, PC, Console","~65M MAU","4.5★","3 - Quality Performers","Console-quality mobile. Generous F2P despite gacha",[3,3,2,2,3,3,3,2,2,2,5,5,4,2,2,3,3,4]],
  [25,"Warframe","PC, Console","~80K Concurrent Steam","88% Very Positive","3 - Quality Performers","Longtime F2P success. Player-friendly monetization",[2,4,2,2,3,4,2,3,3,2,4,5,3,2,3,4,3,4]],
  [26,"Honkai: Star Rail","Mobile, PC","~20M MAU","4.6★","3 - Quality Performers","HoYoverse quality. Turn-based RPG excellence",[3,3,2,2,3,3,3,2,2,2,4,4,3,2,2,3,3,4]],
  [27,"Hollow Knight: Silksong","PC, Console","N/A (Unreleased/Hyped)","96% Overwhelmingly Positive","3 - Quality Performers","2025 Steam GOTY. Years of organic anticipation",[4,3,2,4,4,5,3,5,4,4,2,3,2,0,1,2,2,2]],
  [28,"Monster Hunter Wilds","PC, Console","~200K Concurrent","~89% Very Positive","3 - Quality Performers","Massive Feb 2025 launch. 60M Twitch hours",[3,4,2,3,4,4,3,4,3,3,3,4,3,1,3,3,4,3]],
  [29,"Apex Legends","PC, Console","100-200K Concurrent","67% Mixed","3 - Quality Performers","⚠️ Popular but poor user score. Cheating/server complaints",[1,5,2,1,3,4,1,3,2,2,4,4,3,3,4,4,3,4]],
  [30,"Terraria","PC, Console","40-60K Concurrent","97% Overwhelmingly Positive","3 - Quality Performers","$10 indie legend. Active 900K+ subreddit",[4,3,1,3,4,4,4,3,3,3,3,4,3,1,1,2,4,3]],
  [31,"Elden Ring","PC, Console","50-80K Concurrent","93% Very Positive","4 - Strong Performers","2022 GOTY with lasting power",[3,4,3,4,5,5,2,5,4,5,3,4,3,2,4,3,2,3]],
  [32,"Call of Duty Mobile","Mobile","~20M MAU","4.5★ iOS","4 - Strong Performers","Console-quality FPS on mobile",[1,5,3,1,2,4,1,2,2,2,4,4,3,4,5,5,3,4]],
  [33,"Subway Surfers","Mobile","~35M DAU","4.5★","4 - Strong Performers","11+ years, 3B lifetime downloads",[3,3,0,2,2,3,3,2,2,1,4,3,2,0,0,3,1,3]],
  [34,"Clash of Clans","Mobile","~25M MAU","4.6★","4 - Strong Performers","12+ years relevant. Fair progression",[2,3,1,2,3,3,2,3,3,2,4,4,3,1,2,3,3,4]],
  [35,"8 Ball Pool","Mobile","~10M DAU","4.5★","4 - Strong Performers","Skill-based longevity",[3,2,0,3,4,4,3,3,3,3,3,2,1,0,0,2,3,2]],
  [36,"Ludo King","Mobile","~15M DAU","4.3★","4 - Strong Performers","Cultural phenomenon in India",[3,2,0,3,2,3,4,3,3,2,3,2,1,0,0,2,5,2]],
  [37,"Cyberpunk 2077","PC, Console","30-50K Concurrent","86% Very Positive","4 - Strong Performers","Redemption story. Recovered from disastrous launch",[3,4,3,2,4,4,3,3,3,3,3,5,4,3,4,4,2,4]],
  [38,"Dead by Daylight","PC, Console","40-60K Concurrent","79% Mostly Positive","4 - Strong Performers","Asymmetric horror staple",[2,4,4,2,3,4,1,4,3,3,4,4,3,3,3,4,4,4]],
  [39,"Red Dead Redemption 2","PC, Console","40K Concurrent Steam","92% Very Positive","4 - Strong Performers","Rockstar quality. Years of sustained engagement",[4,3,3,3,4,4,4,3,3,3,3,5,4,2,4,3,2,4]],
  [40,"Palworld","PC, Console","30-50K Concurrent","83% Very Positive","4 - Strong Performers","Jan 2024 viral hit settled to steady base",[3,3,2,2,3,3,3,2,3,2,4,4,3,2,3,3,4,4]],
  [41,"Bongo Cat","PC","~10K Daily","95% Overwhelmingly Positive","5 - Platform Staples","2025 viral casual hit",[4,2,0,3,2,4,5,2,3,1,2,2,1,0,0,2,3,2]],
  [42,"Euro Truck Simulator 2","PC","30-50K Concurrent","97% Overwhelmingly Positive","5 - Platform Staples","Niche perfection",[4,1,1,4,2,4,5,3,4,2,3,4,3,0,0,1,2,3]],
  [43,"Schedule I","PC","~20K Concurrent","97% Overwhelmingly Positive","5 - Platform Staples","2025's highest-rated game. Drug dealer sim phenomenon",[2,4,3,2,4,4,2,3,3,3,4,4,3,4,3,3,3,4]],
  [44,"R.E.P.O.","PC","20-40K Concurrent","96% Overwhelmingly Positive","5 - Platform Staples","$147M gross. Friendslop co-op success",[3,4,2,3,3,4,4,3,3,3,3,3,2,1,2,3,5,3]],
  [45,"Team Fortress 2","PC","50-70K Concurrent","93% Very Positive","5 - Platform Staples","17 years old. Community maintains it",[2,4,2,2,3,4,3,3,3,2,3,3,2,2,3,4,4,3]],
  [46,"Geometry Dash","PC, Mobile","40-50K Concurrent","96% Overwhelmingly Positive","5 - Platform Staples","Rhythm game phenomenon",[3,4,1,4,3,5,2,5,4,4,3,3,2,0,0,3,2,3]],
  [47,"RimWorld","PC","15-20K Concurrent","98% Overwhelmingly Positive","5 - Platform Staples","Colony sim legend",[3,3,2,3,5,4,3,4,4,4,4,5,3,2,2,2,2,4]],
  [48,"Left 4 Dead 2","PC","20-30K Concurrent","98% Overwhelmingly Positive","5 - Platform Staples","15-year-old classic still active",[2,4,3,2,3,4,3,3,3,2,3,3,2,2,4,4,5,3]],
  [49,"Project Zomboid","PC","20-30K Concurrent","95% Overwhelmingly Positive","5 - Platform Staples","Survival depth",[2,3,3,3,4,4,2,4,4,3,4,5,3,2,3,3,3,4]],
  [50,"VRChat","PC (VR)","20-30K Concurrent Steam","~80% Very Positive","5 - Platform Staples","Social VR dominance",[3,3,1,2,2,2,3,2,2,2,4,4,4,2,1,3,5,4]],
  [51,"Mario Kart 8 Deluxe/World","Switch","60M+ Sold","High","6 - Console Dominant","Best-selling Switch game",[4,4,0,3,3,4,4,3,3,2,2,2,1,0,0,3,5,2]],
  [52,"Pokémon Scarlet/Violet/Z-A","Switch","25M+ Sold","Mixed (technical issues)","6 - Console Dominant","Sales vs satisfaction gap",[3,3,1,2,3,3,3,2,3,2,3,4,3,1,1,3,3,3]],
  [53,"Animal Crossing: New Horizons","Switch","45M+ Sold","High","6 - Console Dominant","2M+ subreddit, enforced positivity",[5,1,0,4,3,3,5,3,4,2,3,4,3,0,0,1,4,3]],
  [54,"Super Smash Bros. Ultimate","Switch","34M+ Sold","High","6 - Console Dominant","Fighting game community staple",[3,4,1,2,4,4,3,4,3,3,2,3,2,1,2,4,5,2]],
  [55,"Zelda: Tears of the Kingdom","Switch","20M+ Sold","Very High","6 - Console Dominant","2023 masterpiece",[5,3,1,4,5,5,4,4,4,4,2,4,3,0,1,2,2,3]],
  [56,"Splatoon 3","Switch","12M+ Sold","High","6 - Console Dominant","Unique shooter",[3,4,1,2,3,4,3,3,3,2,3,3,2,1,2,3,4,3]],
  [57,"EA Sports FC 26","PC, Console","40-80K Concurrent Steam","~70% Mixed","6 - Console Dominant","Sports franchise inertia",[2,4,1,2,3,3,2,3,3,2,4,4,2,1,1,3,4,4]],
  [58,"Hogwarts Legacy","All platforms","24M+ Sold","High","6 - Console Dominant","Legs despite controversy",[4,3,2,3,4,4,4,3,3,3,3,4,4,1,2,3,2,3]],
  [59,"Rainbow Six Siege X","PC, Console","40-60K Concurrent","~73% Mostly Positive","6 - Console Dominant","Tactical shooter continues",[1,5,3,2,4,5,1,4,4,3,4,4,3,2,4,4,3,4]],
  [60,"Forza Horizon 5","PC, Xbox, PS","8-10M MAU","High","6 - Console Dominant","Racing excellence",[4,3,0,3,3,4,4,3,3,2,3,3,2,0,0,3,3,3]],
  [61,"War Thunder","PC","50-80K Concurrent","65% Mixed","7 - Live Service (Caveats)","⚠️ High engagement, poor user score. Monetization complaints",[2,4,3,2,4,4,1,4,3,3,4,5,3,2,4,4,2,4]],
  [62,"Helldivers 2","PC, PS","20-40K Concurrent","77% Mostly Positive","7 - Live Service (Caveats)","⚠️ Dropped from 90%+ due to PSN controversy",[2,5,2,2,3,4,3,3,3,3,3,4,2,2,4,4,5,3]],
  [63,"Destiny 2","All platforms","30-50K Concurrent","Mixed","7 - Live Service (Caveats)","Content vault controversy",[2,4,2,1,3,4,2,3,3,2,4,5,3,2,3,4,4,4]],
  [64,"FIFA/EA FC franchise","All platforms","10M+ DAU","~65-70%","7 - Live Service (Caveats)","Annual release fatigue",[2,4,1,2,3,3,2,3,3,2,4,4,2,1,1,3,4,4]],
  [65,"The Sims 4","PC","20-30K Concurrent Steam","~82% Very Positive","7 - Live Service (Caveats)","F2P base model now",[4,2,1,3,3,3,4,2,3,2,4,5,4,1,0,2,2,4]],
  [66,"ARK: Survival Ascended","PC","20-30K Concurrent","65% Mixed","7 - Live Service (Caveats)","⚠️ Paid remake controversy",[2,4,2,2,3,3,2,3,3,2,4,5,3,2,3,3,4,4]],
  [67,"Last War: Survival","Mobile","$2.2B (#2 globally)","4.3★","8 - Mobile Revenue (Concerns)","⚠️ CAUTION: Whale-driven. Heavy pay-to-progress",[1,4,3,0,2,2,1,2,1,1,5,5,3,3,3,4,2,5]],
  [68,"Whiteout Survival","Mobile","$1.9B (#4 globally)","4.5★","8 - Mobile Revenue (Concerns)","⚠️ CAUTION: Same concerns as Last War",[1,4,3,0,2,2,1,2,1,1,5,5,3,3,3,4,2,5]],
  [69,"MONOPOLY GO!","Mobile","$1B+ Revenue","4.5★","8 - Mobile Revenue (Concerns)","Strong IP, event-driven spending",[2,3,1,1,2,2,2,2,2,1,5,4,2,2,1,3,3,4]],
  [70,"Coin Master","Mobile","15M+ MAU","4.6★","8 - Mobile Revenue (Concerns)","⚠️ Gambling-like mechanics",[1,3,2,0,1,2,1,1,1,1,5,4,3,3,1,4,2,5]],
  [71,"Block Blast!","Mobile","356M Downloads","4.6★","8 - Mobile Revenue (Concerns)","⚠️ Downloads vs revenue mismatch",[3,2,1,2,3,3,3,2,2,1,4,3,2,0,0,3,1,3]],
  [72,"Pokémon GO","Mobile","~80M MAU","4.0★","8 - Mobile Revenue (Concerns)","Declining engagement, event-driven",[3,3,1,2,2,3,3,2,2,2,4,3,2,1,0,2,3,4]],
  [73,"Clair Obscur: Expedition 33","PC, Console","N/A (2025 Release)","94% Very Positive","9 - Quality Single-Player","TGA GOTY 2025 winner",[4,3,2,3,4,4,4,3,4,4,2,3,3,1,2,3,3,3]],
  [74,"Kingdom Come: Deliverance II","PC","~100K Concurrent Launch","~88% Very Positive","9 - Quality Single-Player","Twitch drops boosted launch",[3,3,3,3,5,4,3,4,4,4,3,5,4,2,4,3,2,4]],
  [75,"Battlefield 6","PC, Console","~100K Concurrent","~82% Very Positive","9 - Quality Single-Player","Franchise redemption",[1,5,3,1,3,4,1,3,2,2,4,4,3,3,4,4,3,4]],
  [76,"Total War: Warhammer III","PC","25-30K Concurrent","~75% Mostly Positive","9 - Quality Single-Player","Strategy depth",[2,4,3,2,5,4,2,4,4,3,4,5,3,2,3,3,2,4]],
  [77,"Hearts of Iron IV","PC","30-50K Concurrent","93% Very Positive","9 - Quality Single-Player","Paradox grand strategy",[2,3,2,3,5,4,3,4,4,3,3,5,3,1,2,2,2,4]],
  [78,"Civilization VI","PC","60-80K Concurrent","88% Very Positive","9 - Quality Single-Player","4X evergreen",[3,3,1,3,5,4,3,4,4,3,4,5,3,1,2,2,2,5]],
  [79,"Football Manager 26","PC","40-60K Concurrent","~88% Very Positive","9 - Quality Single-Player","Simulation excellence",[3,3,0,3,5,4,3,4,4,3,4,5,3,0,0,2,2,4]],
  [80,"Fallout 4","PC, Console","20-30K Concurrent","~82% Very Positive","9 - Quality Single-Player","Amazon show revival",[3,3,3,2,4,4,3,3,3,3,4,5,4,3,3,3,2,4]],
  [81,"PEAK","PC","~10K Concurrent","90%+ Positive","10 - Rising Stars","2025 viral climbing sim",[4,3,1,4,3,5,3,5,4,4,2,3,2,0,0,2,3,2]],
  [82,"Delta Force","PC, Mobile","~100K Concurrent","~75% Mostly Positive","10 - Rising Stars","Tencent FPS revival",[1,5,3,1,3,4,1,3,2,2,4,4,3,3,4,4,3,4]],
  [83,"Deep Rock Galactic","PC, Console","15-20K Concurrent","97% Positive","10 - Rising Stars","Community gold standard. Rock and Stone culture",[4,4,1,3,3,4,5,3,3,3,3,3,2,1,2,3,5,2]],
  [84,"FFXIV","PC, Console","~1M Active Subs","Very High","10 - Rising Stars","MMO with legendary community support",[3,3,2,2,3,3,3,3,3,3,4,5,4,1,2,3,5,4]],
  [85,"Where Winds Meet","PC","N/A (Niche)","~75% Mostly Positive","10 - Rising Stars","Chinese action RPG newcomer",[3,4,2,2,3,4,3,3,3,3,3,4,3,2,3,3,3,3]],
  [86,"7 Days to Die","PC","30-50K Concurrent","88% Very Positive","10 - Rising Stars","Survival longtime hit",[2,4,3,3,4,4,2,4,3,3,4,5,3,2,3,3,4,4]],
  [87,"Township","Mobile","15M+ MAU","4.5★","10 - Rising Stars","Fair casual game",[3,2,1,2,2,3,3,2,3,1,4,4,2,0,0,2,2,4]],
  [88,"Among Us","All platforms","6-10K Concurrent Steam","4.3★","10 - Rising Stars","Cultural impact, minimal monetization",[3,3,1,3,4,4,4,3,3,4,2,2,1,1,1,2,5,2]],
  [89,"Hay Day","Mobile","4M+ MAU","Supercell quality","10 - Rising Stars","Classic farm sim",[3,2,1,2,2,3,3,2,2,1,4,4,2,0,0,2,2,4]],
  [90,"Stumble Guys","Mobile, PC","15M+ MAU","Fun party game","10 - Rising Stars","Genuine casual appeal",[3,4,0,2,2,3,4,3,2,2,3,2,1,0,0,3,4,2]],
  [91,"Pizza Ready","Mobile","5M+ DAU","4.5★","11 - Completing 100","2025 hybrid-casual hit",[3,3,0,2,2,3,3,2,2,1,3,3,2,0,0,3,1,3]],
  [92,"Vita Mahjong","Mobile","1M+ DAU","Good","11 - Completing 100","Genre resurgence (+189% YoY)",[4,2,0,3,4,4,4,3,3,2,3,3,2,0,0,2,2,2]],
  [93,"Dragon Quest XI","All platforms","6.5M+ Sold","Very High","11 - Completing 100","JRPG excellence",[4,3,1,3,4,4,4,3,4,3,2,4,3,0,1,2,3,3]],
  [94,"Gran Turismo 7","PlayStation","150K+ Daily Drivers","Recovered","11 - Completing 100","⚠️ 87 critic vs 2.5 user at launch. Now improved",[3,3,1,3,3,4,3,3,3,2,3,4,2,0,0,3,3,3]],
  [95,"Asphalt 9","Mobile","4M+ MAU","Quality racing","11 - Completing 100","Quality mobile racer",[2,4,1,2,2,3,2,2,2,1,4,3,2,1,1,4,2,3]],
  [96,"DOOM: The Dark Ages","PC, Console","N/A (Pre-release)","~85%","11 - Completing 100","Franchise continues strong",[2,5,4,2,3,5,2,4,3,3,3,3,2,3,5,5,2,3]],
  [97,"Avowed","PC, Xbox","N/A (Pre-release)","80 OpenCritic","11 - Completing 100","Obsidian RPG solid",[3,3,2,3,4,4,3,3,3,3,3,4,3,2,3,3,3,3]],
  [98,"Ghost of Yotei","PlayStation","N/A (Pre-release)","TBD","11 - Completing 100","2025 Sony flagship",[3,4,3,3,4,4,3,4,3,3,3,4,3,2,4,3,2,3]],
  [99,"Dispatch","PC","N/A (Indie)","97% Steam, 9.0 MC User","11 - Completing 100","Rare perfect alignment",[4,3,1,3,4,4,4,3,4,3,2,3,2,0,1,2,3,2]],
  [100,"Sea of Thieves","PC, Console","15-20K Concurrent Steam","Solid","11 - Completing 100","Rare's pirate sandbox endures",[3,4,2,2,3,3,4,3,3,3,3,4,3,1,2,3,5,3]]
];

export const loadData = (): Game[] => {
  return RAW_GAMES_DATA.map((row, index) => {
    const [rank, title, platform, activePlayers, rating, tier, note, attrs] = row;
    
    // Attribute mapping from CSV order to Interface
    const gameAttributes: GameAttributes = {
      sattva: attrs[0],
      rajas: attrs[1],
      tamas: attrs[2],
      vairagya: attrs[3],
      viveka: attrs[4],
      ekagrata: attrs[5],
      santosha: attrs[6],
      frustrationTolerance: attrs[7],
      impulseControl: attrs[8],
      egoConfrontation: attrs[9],
      addictionPotential: attrs[10],
      timeWasting: attrs[11],
      dissociation: attrs[12],
      samskaraFormation: attrs[13],
      ahimsaViolation: attrs[14],
      pratyaharaDisturbance: attrs[15],
      sanga: attrs[16],
      sankalpaUndermining: attrs[17]
    };

    // Use specific description if available, otherwise fallback to generic
    const specificDescription = GAME_DESCRIPTIONS[title];
    const description = specificDescription 
      ? specificDescription
      : `${title} is a ${tier.split(' - ')[1] || 'popular'} game available on ${platform}.`;

    return {
      id: `game-${index}`,
      rank: rank,
      title: title,
      tier: tier,
      platform: platform,
      activePlayers: activePlayers,
      originalRating: rating,
      description: description,
      criticism: note,
      attributes: gameAttributes,
      yogicScore: calculateScore(gameAttributes),
      userRatings: [],
    };
  }).sort((a, b) => b.yogicScore - a.yogicScore); // Sort by Score default
};